apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validation-lxcfs-admission-webhook-cfg
  labels:
    app: lxcfs-admission-webhook
webhooks:
  - name: validation.lxcfs-admission-webhook.aliyun.com
    clientConfig:
      service:
        name: lxcfs-admission-webhook
        namespace: ${NAMESPACE}
        path: "/validate"
      caBundle: ${CA_BUNDLE}
    sideEffects: None
    admissionReviewVersions: ["v1"]
    rules:
      - operations: [ "CREATE" ]
        apiGroups: ["pod", ""]
        apiVersions: ["v1"]
        resources: ["pods"]
    namespaceSelector:
      matchLabels:
        lxcfs-admission-webhook: enabled
